apiVersion: v1
kind: Service
metadata:
  name: edge-api-gateway
  labels:
    run: edge-api-gateway
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: edge-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-api
  labels:
    app: edge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-api
  template:
    metadata:
      labels:
        app: edge-api
    spec:
      containers:
      - name: edge-api
        image: edge-api
        ports:
        - containerPort: 80