apiVersion: v1
kind: Service
metadata:
  name: angular-app-gateway
  labels:
    run: angular-app-gateway
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: angular-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: angular-nginx
        ports:
        - containerPort: 80
